config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :checkouts, only: [:index]
  mount Rich::Engine => '/rich', :as => 'rich'
  #mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  
  devise_for :admin,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  resources :paypals, only: [:index,:create]
  match '/reply_sms' => 'application#reply_sms' ,via: [:post,:get]
  #match "/users" => "users#index", via: [:get, :post]

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
before_action :authenticate_user!

	def index
		  @order_items = current_order.order_items
	end
	
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/index.html.erb
 

<div class="well">
<% @order_items.each do |order_item| %>

  <div class="row">
    <div class="col-xs-4">
      <h4><%= order_item.product.name %></h4>
    </div>
     <div class="col-xs-4">
      <h4><%= order_item.quantity %> X <%= number_to_currency order_item.unit_price %></h4>
    </div>
    <div class="col-xs-4">      
        <h4 class="text-right"><%= number_to_currency order_item.total_price %><span style="color: green"></span></h4>        
    </div>
    <hr>
  </div>
  <% end %>
  <h3 class="text-right" style="color: red"><%="Total : #{number_to_currency current_order.subtotal} " %></h3>
  <%= link_to "Place Order", paypals_path, :class =>"btn btn-success" %>
  </div>