config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :checkouts, only: [:index]
  mount Rich::Engine => '/rich', :as => 'rich'
  #mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  
  devise_for :admin,
  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  #devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  resources :paypals, only: [:index,:create]
  match '/reply_sms' => 'application#reply_sms' ,via: [:post,:get]
  #match "/users" => "users#index", via: [:get, :post]

end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCart</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1>Admin Login</h1>
      </div>
     
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCartExample</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "My Store", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
      <div class="col-xs-6 text-right">
       <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
          
          
          <li>  <%= link_to "Signed in as #{current_user.email}",  edit_user_registration_path%></li>
              <li>  <%= link_to "Not you? Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>            
          <% end %>
        </ul>
      </div>
    </div>
      <% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
    <hr>

    <%= yield %>
  </div>

</body>
</html>